package silk

const SILK_NO_ERROR = 0
const SILK_ENC_INPUT_INVALID_NO_OF_SAMPLES = -101
const SILK_ENC_FS_NOT_SUPPORTED = -102
const SILK_ENC_PACKET_SIZE_NOT_SUPPORTED = -103
const SILK_ENC_PAYLOAD_BUF_TOO_SHORT = -104
const SILK_ENC_INVALID_LOSS_RATE = -105
const SILK_ENC_INVALID_COMPLEXITY_SETTING = -106
const SILK_ENC_INVALID_INBAND_FEC_SETTING = -107
const SILK_ENC_INVALID_DTX_SETTING = -108
const SILK_ENC_INVALID_CBR_SETTING = -109
const SILK_ENC_INTERNAL_ERROR = -110
const SILK_ENC_INVALID_NUMBER_OF_CHANNELS_ERROR = -111
const SILK_DEC_INVALID_SAMPLING_FREQUENCY = -200
const SILK_DEC_PAYLOAD_TOO_LARGE = -201
const SILK_DEC_PAYLOAD_ERROR = -202
const SILK_DEC_INVALID_FRAME_SIZE = -203
